/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package company;
import java.awt.Color;
import java.sql.*;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
/**
 *
 * @author HITESH
 */
class Myverify extends javax.swing.InputVerifier
{
    public boolean verify(JComponent jc)
    {
        javax.swing.JTextField jt=(javax.swing.JTextField)jc;
     String s=jt.getText();
     if(s.equals(""))
     {  JOptionPane.showMessageDialog(null,"Please Enter The Values","Wrong Input",JOptionPane.INFORMATION_MESSAGE);   
         return false;
     }   
else
    return true;
    }
}
public class registerfrm extends javax.swing.JInternalFrame {
Myverify m1;
    /**
     * Creates new form registerfrm
     */
    public registerfrm(){
        initComponents();
        c1.setVisible(false);
        l1.setVisible(false);
        t7.setVisible(false);
        m1=new Myverify();
       t1.setInputVerifier(m1);
       t2.setInputVerifier(m1);
       t3.setInputVerifier(m1);
       t6.setInputVerifier(m1);
       try
       {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
          Connection  c=DriverManager.getConnection("jdbc:odbc:company");
            Statement st=c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet rs=st.executeQuery("Select max(dno) from department");
            rs.next();
            int n=rs.getInt(1);
            n++;
            t1.setText(""+n);
            rs.close();
            t1.setEditable(false);
       }
       catch(Exception e)
       {
       }
       
        
    }
    
    public registerfrm(String s) {
        initComponents();
          m1=new Myverify();
       t1.setInputVerifier(m1);
       t2.setInputVerifier(m1);
       t3.setInputVerifier(m1);
       t6.setInputVerifier(m1);
       t7.setInputVerifier(m1);
       if(s.equals("UPDATE"))
       {
           l1.setVisible(false);
        t7.setVisible(false);
       
        this.setTitle("UPDATE FORM");
        b1.setLabel(s);
        try
        {
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
          Connection  c=DriverManager.getConnection("jdbc:odbc:company");
            Statement st=c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet rs=st.executeQuery("Select dno from department");
                    while(rs.next())
                    {
                        c1.addItem(rs.getInt(1));
                    }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }
       else if(s.equals("DELETE"))
        {
            l1.setVisible(true);
        t7.setVisible(true);
        c1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        t1.setVisible(false);
        t2.setVisible(false);
        t3.setVisible(false);
        t6.setVisible(false);
        this.setTitle("DELETE FORM");
        b1.setLabel(s);
        
    }
       else if(s.equals("EMPDELETE"))
       {
            l1.setVisible(true);
            l1.setText("Enter The Employee id");
        t7.setVisible(true);
        c1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        l4.setVisible(false);
        l5.setVisible(false);
        t1.setVisible(false);
        t2.setVisible(false);
        t3.setVisible(false);
        t6.setVisible(false);
        this.setTitle("DELETE FORM");
        b1.setLabel("DELETE RECORD");
       }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        c1 = new javax.swing.JComboBox();
        l1 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("REGISTER FORM");

        l2.setText("Department Number");

        l3.setText("Department Name");

        l4.setText("Department Location");

        l5.setText("Email");

        t1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        t2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        t3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        t6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });

        b1.setText("REGISTER");
        b1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                me(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mx(evt);
            }
        });
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        l1.setText("Enter The Department Number");

        t7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(l2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l4, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(l5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(t1)
                            .addComponent(t3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l1)
                    .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l2)
                    .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l3)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l4)
                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(l5)
                    .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
String s;
s=evt.getActionCommand();
if(s.equals("REGISTER"))
{
        try
{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
    Connection c=DriverManager.getConnection("jdbc:odbc:company");
    Statement st=c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
    int j=JOptionPane.showConfirmDialog(this,"Are You Sure To Register","CONFIRMATION",JOptionPane.YES_NO_OPTION);
    if(j==JOptionPane.YES_OPTION)
    {
    int i = st.executeUpdate("Insert into department values("+Integer.parseInt(""+t1.getText())+",'"+t2.getText()+"','"+t3.getText()+"',"+0+",'"+t6.getText()+"')");

    }
    t1.setText("");
t2.setText("");
t3.setText("");
t6.setText("");
 JOptionPane.showMessageDialog(this,"Data Entered!!!","SUCCESSFULL",JOptionPane.INFORMATION_MESSAGE);
}
        catch(Exception e)
{
    System.out.println();
}
}
else if(s.equals("UPDATE"))
{
    try
{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
    Connection c=DriverManager.getConnection("jdbc:odbc:company");
    Statement st1=c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
    int j=JOptionPane.showConfirmDialog(this,"Are You Sure To Update!!","CONFIRMATION",JOptionPane.YES_NO_OPTION);
    if(j==JOptionPane.YES_OPTION)
    {
        int i = st1.executeUpdate("update department set dno="+Integer.parseInt(t1.getText())+",dname='"+t2.getText()+"',dloc='"+t3.getText()+"',noofemp="+0+",email='"+t6.getText()+"' where dno="+Integer.parseInt(t1.getText())+"");
    } 
}
    catch(Exception e)
{
    System.out.println();
}
}
else if(s.equals("DELETE"))
  {
    try
{
    Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
    Connection c=DriverManager.getConnection("jdbc:odbc:company");
    Statement st1=c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
    int j=JOptionPane.showConfirmDialog(this,"Are You Sure To Delete!!","CONFIRMATION",JOptionPane.YES_NO_OPTION);
    if(j==JOptionPane.YES_OPTION)
    {
        int i = st1.executeUpdate("delete from department where dno="+t7.getText()+"");
    }
    t7.setText("");
}
    catch(Exception e)
{
    System.out.println();
}
}
    }//GEN-LAST:event_b1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
  try
  {
      int i=(int)c1.getSelectedItem();
       Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
          Connection  c=DriverManager.getConnection("jdbc:odbc:company");
            Statement st=c.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet rs=st.executeQuery("Select * from department where dno="+i);
            if(rs.next())
            {
                t1.setText(""+rs.getInt(1));
                t2.setText(rs.getString(2));
                t3.setText(rs.getString(3));
                t6.setText(rs.getString(5));
            }
  }
  catch(Exception e)
  {
  System.out.println(e);
  }
  
                                      
       
    }//GEN-LAST:event_c1ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    private void me(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_me
    b1.setBackground(Color.DARK_GRAY);  
    b1.setForeground(Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_me

    private void mx(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mx
  b1.setBackground(Color.LIGHT_GRAY);
  b1.setForeground(Color.BLACK);        // TODO add your handling code here:
    }//GEN-LAST:event_mx

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JComboBox c1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    // End of variables declaration//GEN-END:variables
}
